# Generated by Django 4.0.5 on 2022-06-17 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='album')),
                ('image', models.ImageField(upload_to='', verbose_name='album_image')),
                ('release_date', models.DateField()),
                ('num_stars', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='band_title')),
                ('image', models.ImageField(upload_to='images', verbose_name='band_image')),
                ('description', models.TextField(verbose_name='band_description')),
            ],
            options={
                'verbose_name': 'Band',
                'verbose_name_plural': 'Bands',
            },
        ),
        migrations.CreateModel(
            name='BandMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='bad_member_name')),
                ('surname', models.CharField(max_length=20, verbose_name='band_member_surname')),
                ('biography', models.TextField(verbose_name='band_member_biography')),
                ('instrument', models.CharField(max_length=30, verbose_name='band_member_instrument')),
            ],
            options={
                'verbose_name': 'Band member',
                'verbose_name_plural': 'Band members',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='genre_title')),
                ('description', models.TextField(verbose_name='genre_description')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='song_title')),
                ('lyrics', models.TextField(max_length=3000, verbose_name='song_lyrics')),
                ('description', models.TextField(blank=True, max_length=4000, null=True, verbose_name='song_description')),
                ('audio_file', models.FileField(upload_to='music')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album')),
                ('genre', models.ManyToManyField(related_name='song', to='music.genre', verbose_name='song_genre')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.band'),
        ),
    ]
