# Generated by Django 4.0.5 on 2022-06-27 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandmember',
            name='band',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='music.band'),
            preserve_default=False,
        ),
    ]
