# Generated by Django 4.0.5 on 2022-07-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_album_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='num_stars',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
